# Admittance parameters for two mass damper systems 
# (the arm and the platform) with params (mass_arm, damping_arm) 
# and (mass_platform, damping_platform) respectively, connected by a 
# spring-damper with parameters (damping_coupling, stiffness_coupling, 
# equilibrium_point_spring)

# mass_platform: [10,0,0,0,0,0,
#                 0,10,0,0,0,0,
#                 0,0,10,0,0,0,
#                 0,0,0,5,0,0,
#                 0,0,0,0,5,0,
#                 0,0,0,0,0,5]

mass_platform: [40,0,0,0,0,0,
                0,10,0,0,0,0,
                0,0,20,0,0,0,
                0,0,0,5,0,0,
                0,0,0,0,5,0,
                0,0,0,0,0,20]

# mass_arm: [0.8,0,0,0,0,0,
#            0,0.8,0,0,0,0,
#            0,0,0.8,0,0,0,
#            0,0,0,.2,0,0,
#            0,0,0,0,.2,0,
#            0,0,0,0,0,.1]

mass_arm: [8.0,0,0,0,0,0,
           0,8.0,0,0,0,0,
           0,0,8.0,0,0,0,
           0,0,0,2.0,0,0,
           0,0,0,0,2.0,0,
           0,0,0,0,0,2.0]

damping_coupling: [0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0,
                   0,0,0,0,0,0]

damping_platform: [200,0,0,0,0,0,
                   0,50,0,0,0,0,
                   0,0,50,0,0,0,
                   0,0,0,50,0,0,
                   0,0,0,0,50,0,
                   0,0,0,0,0,50]

# damping_arm: [25,0,0,0,0,0,
#   0,25,0,0,0,0,
#   0,0,25,0,0,0,
#   0,0,0,5,0,0,
#   0,0,0,0,5,0,
#   0,0,0,0,0,5]

damping_arm: [60,0,0,0,0,0,
              0,180,0,0,0,0,
              0,0,60,0,0,0,
              0,0,0,20,0,0,
              0,0,0,0,20,0,
              0,0,0,0,0,20]


# stiffness_coupling: [150,0,0,0,0,0,
#                      0,150,0,0,0,0,
#                      0,0,150,0,0,0,
#                      0,0,0,5,0,0,
#                      0,0,0,0,5,0,
#                      0,0,0,0,0,5]

stiffness_coupling: [100,0,0,0,0,0,
                     0,300,0,0,0,0,
                     0,0,60,0,0,0,
                     0,0,0,10,0,0,
                     0,0,0,0,10,0,
                     0,0,0,0,0,5]

#equilibrium_point_spring: [0.0478,0.3477,0.5611,0.7527, 0.6979, 0.01073, -0.033988]



# [position (x, y, z)  orientation (x, y, z, w)]
#equilibrium_point_spring: [0.1,0.4,0.5,-0.593599, -0.566706, -0.369419, 0.435908]


# this equilibrium point is derived from setting all joints to -90 degree
equilibrium_point_spring: [0.111,0.494,0.387,      0.707, 0.004, 0.707, 0.010]
#equilibrium_point_spring: [0.211,0.65,0.21,      0.707, 0.004, 0.707, 0.010]



# pose: 
#   position: 
#     x: 0.111958708113
#     y: 0.49448825331
#     z: 0.587105004424
#   orientation: 
#     x: 0.706139824652
#     y: 0.00495619074876
#     z: 0.707969920618
#     w: 0.0109806972969

# not that position is defined in "ur5_arm_base_link"
# with x pointing right
#      y pointing forward
#      z pointing up


# this will limit the workspace ([x_min x_max y_min y_max z_min z_max])
# workspace_limits: [-0.30, 0.30, 0.35, 0.55, 0.20, 0.75]
workspace_limits: [-0.40, 0.50, 0.30, 0.80, 0.15, 0.50]

arm_max_vel: 1.5
arm_max_acc: 3.0
platform_max_vel: 0.05
platform_max_acc: 0.2



# object impedance parameters

object_impedance_inertia: [8.0,0,0,0,0,0,
                           0,8.0,0,0,0,0,
                           0,0,8.0,0,0,0,
                           0,0,0,2.0,0,0,
                           0,0,0,0,2.0,0,
                           0,0,0,0,0,2.0]



object_impedance_damping: [100,0,0,0,0,0,
                            0,100,0,0,0,0,
                            0,0,100,0,0,0,
                            0,0,0,30,0,0,
                            0,0,0,0,30,0,
                            0,0,0,0,0,30]



object_impedance_stiffness: [120,0,0,0,0,0,
                             0,120,0,0,0,0,
                             0,0,120,0,0,0,
                             0,0,0,30,0,0,
                             0,0,0,0,30,0,
                             0,0,0,0,0,30]


posture_damping: [12,12,12, 7, 7, 7, 1, 1, 1] 


posture_stiffness: [20,20,20, 10, 10, 10, 1, 1, 1]


disturbance_observer_gain: [50,0,0,0,0,0,
                            0,50,0,0,0,0,
                            0,0,50,0,0,0,
                            0,0,0,50,0,0,
                            0,0,0,0,50,0,
                            0,0,0,0,0,50]